apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  type: default
  interval: 24h
  url: https://traefik.github.io/charts
  timeout: 60s