---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgAwmzB+8IbXqvK5Jfq5bNClpQrhsep52ezNndx8uTuzYsjjYNRPWY81XwvV/dgaUUhMeA6aI0FE3gVJPLFoaHFSkFxQ5WzJJlRcgqHbg1gYkQambiNk6SWfbr4KisFPykRkJD13vUEVZOMTafuiBHixncWnM3bqzW6HdLxt4wzxjiRriByIAHDjenSxnZsd5AME8mGHatHhfF+0Y3wtvnluDlVU66qODKj35FjZMBqr/GcvzW5tBwiW1HGOfdw5Wpc6dHzo/r2BfbxJCMt5EwkNNZp16H2OkMcW4YYXgol4jq/rJw5qdlM7yzJ82uARQULtxOxoa+Nny0hzhMjLOVlp4AdDPE4usGQ6sK34MK2r9yBYPeNsWXDKi66q05rMZAiQGovXJ0vo7avpVpNKbAg1mY17TgGlCj7kfukJaWTwwZkGXhkASs38d3jqiEvAm5PpNJe+5DAkofhTp3auJX8djg8fV3L5fBiPyQXmExcilw+y5NNno0KecTAzn/Dg6O64rUNIKbtTFaOuOa4I3KanPjb9w5wkvZET2qU4LomH1XnSpoktckwnxcuWB9WDncRxHXgGYnWf7Y87NvWb0a+rg0naW527mb0guBKtMgbMiE0uqvZspF9IjjI88PISJ4FKPelhunCUvtttLGBllib6lCAGC/vLgCi9ZfydldcKyJpcMnPLcyzk0PT+OcAHvXW3qtZANkewNADQgsGXqXsn4fyei7jSuuGhUJWemXq6c38Qo0L8eBhn
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
