---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgCi4by6xwujzU2RmrANRXOXjRxzpp3pXzvTFud4QLsehGLTxjqVHiK6pHaW0HXvXgvsBqkxdO6HXEtAnmew53yq4NpTI41enpmd89kSAxqaT9DiQVj4NL0G82J5Md96/dCkKoVkkABC9kMATfJFr9sWdrLl22BRu8sMvjI3oRg1hT5NRZFw4r3Jtvj+Qq4M5JAbKsy9Qdt/kVFC04KzSnvbzVk9jzxKsbAtbvKbrMwUO5rOjdcANXnUZz91gsqlQ+ahfwqXyINImwh3LHcLV64ujHTiinhN3sdBW2TShOCWkyOARs9f4UPaesObuhTxcNfRZV/voC1op0paGDO594W/ghQmoTPoMQDqukLvrR/pKZYOHhFU+61RvFjClaNmqK4W7wGCoSR3BA+zTRyOoAKW52FP6ZIpn1iGVpDX6s4lQgCoUaJoDPo/V7jIV3TOX6Hy/hMDNb+4audesdHOrfX1CgctGtpnVhu2B/afMWJLa1lLiiwQaxwRee6oUowJIxVxJA+wIkr41uwclTQajnr/xhtfbnYJ9ZtLx1+EvtTruppb1y92y+r744Mcc0mugNJ6hNvZ6O3Yap3t7Qx2/UJh/gRYXGQbij+zMyayUvrVUeiOAOWVF2Hag9ykx0AIWH53Y8D6CGJBWC4qHh5ERDEix2513ataVSE75DaoW5Z7GxFHOdqgAIdDiW7vkxXe8iXB557D4OW/u66kIcdAWsO6CTBpltJNtDLsnXML1p40w90sdnNZqGfH
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
