---
# 默认 TLS 配置
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: default
  namespace: traefik
spec:
  minVersion: "VersionTLS12"
  maxVersion: "VersionTLS13"
  cipherSuites:
    - "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
    - "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305"
    - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
  curvePreferences:
    - CurveP521
    - CurveP384
  sslStrategies:
    - "tls.SniStrict"
  alpnProtocols:
    - "h2"
    - "http/1.1"
---
# 默认证书存储（如果需要）
apiVersion: traefik.containo.us/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik
spec:
  defaultCertificate:
    secretName: default-tls-cert  # 需要创建对应的 Secret